# @package _global_

defaults:
  - _self_
  - generator: vaeganvocoder
  - discriminator: univnet
  - train: vaeganvocoder
  - data: namine_ritsu

hydra:
  run:
    dir: ./
  output_subdir: null
  job_logging:
    formatters:
      simple:
        format: "[%(asctime)s][%(levelname)s][%(module)s | %(lineno)s] %(message)s"
    disable_existing_loggers: false

out_dir: # Directory to output training results.
seed: 12345 # Seed number for random numbers.

f0_aug: true
f0_conv_num: 2